services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf
    extra_hosts:
      - host.docker.internal:host-gateway